// This file is auto-generated by env-watcher. Do not edit directly.

const PORT: number = Number(process.env.PORT!);
const STRIPE_API_KEY: string = process.env.STRIPE_API_KEY!;
const FIREBASE_API_KEY: string = process.env.FIREBASE_API_KEY!;

export {
  PORT,
  STRIPE_API_KEY,
  FIREBASE_API_KEY
};
