/**
 * Auto-generated by @React() for route: /user/details/:id
 */


export default function UserController_getUserDetails({props}:{props: any}) {
  
  return (
    <div>
      <h1>Data from /user/details/:id</h1>
      <div>
        <h2>Server Data:</h2>
        <pre>{JSON.stringify(props, null, 2)}</pre>
      </div>
    </div>
  );
}