import React from "react";

    // Auto-generated by @React() for route: /user/
    export default function UserController_getUser({ data }: { data: any }) {
      return (
        <div>
          <h2>Data from /user/</h2>
          <pre>{JSON.stringify(data, null, 2)}</pre>
        </div>
      );
    }