/**
 * Auto-generated by @React() for route: /user/list
 */

// Custom hook to get server props
function useServerProps() {
  return window.__PROPS__ || {};
}

 function UserController_getUserList() {
  const props = useServerProps();
  
  return (
    <div>
      <h1>Data from /user/list</h1>
      <div>
        <h2>Server Data:</h2>
        <pre>{JSON.stringify(props, null, 2)}</pre>
      </div>
      
      {/* Add your custom JSX here */}
      {props.title && <h2>{props.title}</h2>}
      {props.description && <p>{props.description}</p>}
      {props.users && (
        <div>
          <h3>Users:</h3>
          <ul>
            {props.users.map((user, index) => (
              <li key={index}>{user.name || user}</li>
            ))}
          </ul>
        </div>
      )}
    </div>
  );
}