import * as fs from "fs";
import * as path from "path";

export function generateReactView(
  controllerClassName: string,
  methodName: string,
  controllerFilePath: string,
  routePath: string
) {
  const fileDir = path.dirname(controllerFilePath);
  const viewsDir = path.join(fileDir, "views");

  if (!fs.existsSync(viewsDir)) {
    fs.mkdirSync(viewsDir, { recursive: true });
    console.log(`Created directory: ${viewsDir}`);
  }

  const tsxFileName = `${controllerClassName}.${methodName}.tsx`;
  const tsxFilePath = path.join(viewsDir, tsxFileName);
  const componentName = `${controllerClassName}_${methodName}`;

  if (fs.existsSync(tsxFilePath)) {
    return;
  }

  const template = `
/**
 * Auto-generated by @React() for route: ${routePath}
 */


export default function ${componentName}({props}:{props: any}) {
  
  return (
    <div>
      <h1>Data from ${routePath}</h1>
      <div>
        <h2>Server Data:</h2>
        <pre>{JSON.stringify(props, null, 2)}</pre>
      </div>
    </div>
  );
}
`.trim();

  console.log(tsxFileName, tsxFilePath);

  fs.writeFileSync(tsxFilePath, template, "utf8");
  console.log(`✅ Generated React view: ${tsxFileName}`);
}
