import * as fs from "fs";
import * as path from "path";

export function generateReactView(
  controllerClassName: string,
  methodName: string,
  controllerFilePath: string,
  routePath: string
) {
  const fileDir = path.dirname(controllerFilePath);
  const viewsDir = path.join(fileDir, "views");

  if (!fs.existsSync(viewsDir)) {
    fs.mkdirSync(viewsDir, { recursive: true });
    console.log(`Created directory: ${viewsDir}`);
  }

  const jsxFileName = `${controllerClassName}.${methodName}.jsx`;
  const jsxFilePath = path.join(viewsDir, jsxFileName);
  const componentName = `${controllerClassName}_${methodName}`;

  if (fs.existsSync(jsxFilePath)) {
    console.log(`❕ React view already exists: ${jsxFilePath}`);
    return;
  }

  const template = `
/**
 * Auto-generated by @React() for route: ${routePath}
 */

// Custom hook to get server props
function useServerProps() {
  return window.__PROPS__ || {};
}

 function ${componentName}() {
  const props = useServerProps();
  
  return (
    <div>
      <h1>Data from ${routePath}</h1>
      <div>
        <h2>Server Data:</h2>
        <pre>{JSON.stringify(props, null, 2)}</pre>
      </div>
      
      {/* Add your custom JSX here */}
      {props.title && <h2>{props.title}</h2>}
      {props.description && <p>{props.description}</p>}
      {props.users && (
        <div>
          <h3>Users:</h3>
          <ul>
            {props.users.map((user, index) => (
              <li key={index}>{user.name || user}</li>
            ))}
          </ul>
        </div>
      )}
    </div>
  );
}
`.trim();

  fs.writeFileSync(jsxFilePath, template, "utf8");
  console.log(`✅ Generated React view: ${jsxFilePath}`);
}
